### ISSUE TITLE
[PSW] - Prototipagem

### ISSUE THREAD

**Issue by natanbalthazar** [dsm-cefet-rj/trabalho-integrado-2023-2-ti-2023-2-grupo-6#5]
- [x] Discussão das Ideias - Responsável: Todos Fizeram
- [x] Descrição do Business Case - Responsável: Natan
- [x] Processo de Negócio Principal - Responsável: Natan
- [x] Definição das Entidades e seus Responsáveis - Responsável: Natan
- [x] Definição de Casos de Uso e Telas a Projetar - Responsável: Natan
- [x] Matriz Perfil x Funcionalidade
- [x] Construção da Matriz CRUD
- [x] Priorização de Requisitos
