### ISSUE TITLE
[PSW] - Front-End

### ISSUE THREAD

**Issue by natanbalthazar** [dsm-cefet-rj/trabalho-integrado-2023-2-ti-2023-2-grupo-6#6]
# Tarefas a serem realizadas:

## - [] Prototipação em HTML e Responsividade

Telas Gerais:
- [x] Página Inicial - Responsável: Natan 
- [x] Página de Login - Responsável: Natan
- [x] Página de Registro - Responsável: 
- [x] Página de Configurações de Perfil - Responsável: 
- [x] Página de Ajuda e Suporte - Responsável: 

Telas para Alunos (Usuários):
- [x] Página de Início - Responsável:
- [x] Página de Perfil do Aluno - Responsável:
- [x] Página de Busca de Trilhas de Conhecimento - Responsável:
- [x] Página de Detalhes da Trilha de Conhecimento - Responsável:
- [x] Página de Busca de Professores/Monitores - Responsável: 
- [x] Página de Agendamento de Sessões - Responsável: 

Telas para Professores/Monitores (Usuários):
- [x] Página de Perfil do Professor/Monitor - Responsável:
- [x] Página de Gerenciamento de Trilhas de Conhecimento e Monitorias - Responsável:
- [x] Página de Criação/Edição de Trilhas de Conhecimento - Responsável:
- [x] Página de Gerenciamento de Horários - Responsável: 

### - [ ] Criação de Rotas

- [x] Rota dos Perfil dos Professores/Monitores- Responsável: 
- [x] Rota do Perfil do Aluno - Responsável: 
- [x] Rota Agendamento de Sessões  - Responsável: 
- [x] Rota de Cadastro  - Responsável: 
- [x] Rota de Criação/Edição de Trilhas de Conhecimento - Responsável:
- [x] Rota de Busca - Responsável: 
- [x] Rota de Detalhes da Trilha de Conhecimento - Responsável:
- [x] Rota de Login  - Responsável: 
- [x] Rota de Página Inicial - Responsável: 

### - [ ] Gerenciamento de Estado

- [x] Estado dos Professores/Monitores- Responsável: 
- [x] Estado do Perfil - Responsável: 
- [x] Estado de Agendamento de Sessões - Responsável: 
- [x] Estado de Criação/Edição de Trilhas de Conhecimento - Responsável:
- [x] Estado de Busca - Responsável: 
- [x] Estado de Detalhes da Trilha de Conhecimento - Responsável:
- [x] Estado de Detalhes do Professor/Monitor - Responsável:

### - [ ] Gerenciamento de Eventos

- [x] Evento de Informações dos Professores/Monitores - Responsável: 
- [x] Evento de Atualização de Usuário - Responsável: 
- [x] Evento de Agendamento de Sessões - Responsável: 
- [x] Evento de Criação/Edição de Trilhas de Conhecimento
- [x] Evento de Busca - Responsável: 
- [x] Evento de Detalhes da Trilha de Conhecimento - Responsável:
- [x] Evento de Detalhes do Professor/Monitor - Responsável:

### - [ ] Componentização de Páginas

- [x] Página dos Professores/Monitores- Responsável: 
- [x] Página de Perfil do Aluno - Responsável: 
- [x] Página de Agendamento de Sessões - Responsável: 
- [x] Página de Criação/Edição de Trilhas de Conhecimento - Responsável:
- [x] Página de Detalhes da Trilha de Conhecimento - Responsável:
- [x] Página de Busca - Responsável: 
- [x] Página de Login - Responsável: 
- [x] Página Inicial - Responsável:
