### ISSUE TITLE
[PSW] - Back-End

### ISSUE THREAD

**Issue by natanbalthazar** [dsm-cefet-rj/trabalho-integrado-2023-2-ti-2023-2-grupo-6#7]
# Tarefas a serem realizadas:

### - [ ] Criação de Rotas

- [ ] Rota de consulta - Responsável: 
- [ ] Rota de usuário - Responsável: 
- [ ] Rota de profissionais - Responsável: 
- [ ] Rotas de localidade - Responsável: 

### - [ ] Modelagem de Banco de Dados

- [ ] Interação com MongoDB com Back - Responsável: 

### - [ ] Criação de Collections

- [ ] Criação de Collections: Consulta - Responsável: 
- [ ] Criação de Collections: Usuário - Responsável: 
- [ ] Criação de Collections: Profissionais - Responsável: 
- [ ] Criação de Collections: Localidade - Responsável: 

### - [ ] Criação de serviços e operações no MongoDB

- [ ] Serviços de Consulta - Responsável: 
- [ ] Serviços de Profissional  - Responsável: 
- [ ] Serviços de Usuário  - Responsável: 
- [ ] Serviços de Localidade - Responsável: 

### - [ ] Autenticação e Segurança
- [ ] Implementação de Autenticação de Usuários - Responsável:
- [ ] Configuração de Autorizações e Permissões - Responsável:
